language: php

php:
  - 7
  - nightly

env:
  - PHAN_TEST="PhpUnit" TEST_SUITE="AnalyzerTest"
  - PHAN_TEST="PhpUnit" TEST_SUITE="PhanTest"
  - PHAN_TEST="PhpUnit" TEST_SUITE="RasmusTest"
  - PHAN_TEST="PhpUnit" TEST_SUITE="LanguageTest"
  - PHAN_TEST="PhanDatabaseTest"
  - PHAN_TEST="SelfTest"
sudo: false

matrix:
  fast_finish: true
  allow_failures:
    - php: "nightly"

cache:
  directories:
    - ./vendor
    - ./build/ast

before_install:
  - ./tests/setup.sh

install:
  - composer --prefer-source install

script:
  - if [ "$PHAN_TEST" = "PhpUnit" ]; then ./vendor/bin/phpunit --colors --testsuite "$TEST_SUITE"; fi;

  # Build package to some self-test and packaging test
  - php package.php

  # Test phan alanyzing on itself
  - if [ "$PHAN_TEST" = "SelfTest" ]; then php -dmemory_limit=2G build/phan.phar analyze -e vendor/ -r vendor/ -r src/; fi;

  # Test passes with DB enabled
  - if [ "$PHAN_TEST" = "PhanDatabaseTest" ]; then  php -dmemory_limit=2G build/phan.phar analyze --database phan.db -e vendor/ -r vendor/ -r src/; fi;
  - if [ "$PHAN_TEST" = "PhanDatabaseTest" ]; then  php -dmemory_limit=2G build/phan.phar analyze --database phan.db -e vendor/ -r vendor/ -r src/; fi;



before_deploy:
  # Package PHAR package for deployment
  - php package.php

deploy:
  provider: releases
  api_key: $API_KEY
  file: build/phan.phar
  skip_cleanup: true
  on:
    tags: true
